"""AUTO-GENERATED by scripts/generate_factories.py — do not edit by hand."""

from __future__ import annotations

# fmt: off
DEFAULT_TRANSFORM_FACTORIES: dict[str, tuple[str, str]] = {
    "content_profiler": ("lattice.transforms.content_profiler", "ContentProfiler"),
    "runtime_contract": ("lattice.transforms.runtime_contract", "RuntimeContractTransform"),
    "cache_arbitrage": ("lattice.transforms.cache_arbitrage", "CacheArbitrageOptimizer"),
    "reference_sub": ("lattice.transforms.reference_sub", "ReferenceSubstitution"),
    "tool_filter": ("lattice.transforms.tool_filter", "ToolOutputFilter"),
    "output_cleanup": ("lattice.transforms.output_cleanup", "OutputCleanup"),
    "causal_chain": ("lattice.transforms.causal_chain", "CausalChainExtractor"),
    "message_dedup": ("lattice.transforms.message_dedup", "MessageDeduplicator"),
    "context_selector": ("lattice.transforms.context_selector", "SubmodularContextSelector"),
    "diagnostic_rle": ("lattice.transforms.diagnostic_rle", "DiagnosticRLE"),
    "columnar_pack": ("lattice.transforms.columnar_pack", "ColumnarTablePack"),
    "json_shape": ("lattice.transforms.json_shape", "JSONShapeFactor"),
    "rate_distortion": ("lattice.transforms.rate_distortion", "RateDistortionCompressor"),
    "extractive_compress": ("lattice.transforms.extractive_compress", "ExtractiveCompressor"),
    "path_prefix": ("lattice.transforms.path_prefix", "PathPrefixCompressor"),
    "format_conversion": ("lattice.transforms.format_converter", "FormatConverter"),
    "tool_projection": ("lattice.transforms.tool_projection", "QueryAwareProjection"),
    "representation_optimizer": ("lattice.pipeline.representation_optimizer", "RepresentationOptimizer"),
    "ir_structure_optimizer": ("lattice.transforms.optimizers.ir_structure_optimizer", "IRStructureOptimizer"),
    "reference_optimizer": ("lattice.transforms.optimizers.reference_optimizer", "ReferenceOptimizer"),
    "tool_optimizer": ("lattice.transforms.optimizers.tool_optimizer", "ToolOptimizer"),
    "context_optimizer": ("lattice.transforms.optimizers.context_optimizer", "ContextOptimizer"),
    "diagnostic_optimizer": ("lattice.transforms.optimizers.diagnostic_optimizer", "DiagnosticOptimizer"),
}

# fmt: on
