#!/usr/bin/env python3
"""Generate pipeline/_generated_factories.py from transforms/registry.py."""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "src/lattice/pipeline/_generated_factories.py"


def _parse_factory_path(factory_path: str) -> tuple[str, str]:
    mod, _, cls = factory_path.rpartition(".")
    if not mod or not cls:
        raise ValueError(f"invalid factory_path: {factory_path!r}")
    return mod, cls


def main() -> int:
    sys.path.insert(0, str(ROOT / "src"))
    from lattice.transforms.registry import BUILTIN_TRANSFORMS, OPTIMIZER_SPECS

    specs = (*BUILTIN_TRANSFORMS, *OPTIMIZER_SPECS)
    lines: list[str] = [
        '"""AUTO-GENERATED by scripts/generate_factories.py — do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "# fmt: off",
        "DEFAULT_TRANSFORM_FACTORIES: dict[str, tuple[str, str]] = {",
    ]
    for spec in specs:
        if not spec.factory_path or spec.execution_only:
            continue
        mod, cls = _parse_factory_path(spec.factory_path)
        lines.append(f'    "{spec.canonical_name}": ("{mod}", "{cls}"),')
    lines.extend(["}", "", "# fmt: on", ""])
    content = "\n".join(lines)
    if OUT.exists() and OUT.read_text() == content:
        print("generate_factories: up to date")
        return 0
    OUT.write_text(content)
    print(f"generate_factories: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
